source "https://rubygems.org"

gem 'activerecord'
gem 'activerecord-import'
gem 'activemodel'
gem 'activesupport'
gem 'faker'
gem 'jsonapi-serializer'
gem 'standalone_migrations', '~> 7.0'
gem 'pagy'
gem 'pg'
gem 'pry'
gem 'puma'
gem 'rack', '~> 2.0.1'
gem 'rack-parser', :require => 'rack/parser'
gem 'rspec'
gem 'rspec-expectations'
gem 'database_cleaner'
gem 'factory_bot'
gem 'shoulda-matchers'
gem 'nokogiri', '~> 1.13', '>= 1.13.8'
gem 'sidekiq'
gem 'sidekiq-cron'
